
server:
  port:
    8080
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    config-url: /Drone/v3/api-docs/swagger-config
    url: /v3/api-docs


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drone
    username: root
    password: Sintax80
  main:
    allow-circular-references: true



  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update




